receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  otlphttp:
    endpoint: https://tempo-prod-30-prod-us-east-3.grafana.net/tempo
    headers:
      authorization: "Basic __TEMPO_AUTH__"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
