#!/usr/bin/env python3
"""
sync-from-catalog.py — Sync service registry from Grafana Service Catalog.

Fetches all Component entities of type=service from the Grafana Service Catalog
API, extracts metadata, and writes:
  1. service-registry/services.txt  — flat list for shell scripts
  2. terraform/catalog.auto.tfvars  — var.services map for Terraform

Run:
  GRAFANA_URL=https://yourorg.grafana.net \
  GRAFANA_TOKEN=glsa_... \
  python3 scripts/sync-from-catalog.py

Grafana Service Catalog API reference:
  https://grafana.com/docs/grafana-cloud/developer-resources/api-reference/service-catalog/
"""
import argparse
import json
import os
import sys
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import HTTPError, URLError

DEFAULT_TIER               = "2"
DEFAULT_LATENCY_THRESHOLD  = 1.0
DEFAULT_ERROR_THRESHOLD    = 0.05
DEFAULT_SAT_THRESHOLD      = 0.85
DEFAULT_ONCALL_TEAM_SUFFIX = "-sre"
DEFAULT_RUNBOOK_BASE       = "https://runbooks.internal"

TIER1_KEYWORDS = ["payment", "checkout", "auth", "order"]


def get_services(grafana_url: str, token: str) -> list[dict]:
    url = f"{grafana_url.rstrip('/')}/api/catalog/entities?kind=Component&type=service&limit=100"
    req = Request(url, headers={"Authorization": f"Bearer {token}", "Accept": "application/json"})
    try:
        with urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read())
            if isinstance(data, list):
                return data
            return data.get("items", data.get("entities", []))
    except HTTPError as e:
        if e.code == 404:
            print("ERROR: Service Catalog API not found. Ensure the feature is enabled and token has catalog:read.")
        else:
            print(f"ERROR: HTTP {e.code}: {e.reason}")
        sys.exit(1)
    except URLError as e:
        print(f"ERROR: Could not reach {grafana_url}: {e.reason}")
        sys.exit(1)


def infer_service_config(entity: dict) -> dict:
    meta        = entity.get("metadata", {})
    spec        = entity.get("spec", {})
    annotations = meta.get("annotations", {})
    name        = meta.get("name", "unknown-service")
    alliance    = spec.get("system", annotations.get("grafana.com/alliance", "platform"))
    tier        = annotations.get("grafana.com/tier", DEFAULT_TIER)
    if any(kw in name.lower() for kw in TIER1_KEYWORDS):
        tier = "1"
    oncall_team = annotations.get("grafana.com/oncall-team", f"{alliance}{DEFAULT_ONCALL_TEAM_SUFFIX}")
    return {
        "name": name,
        "alliance": alliance,
        "tier": tier,
        "latency_threshold":    float(annotations.get("grafana.com/latency-slo-seconds", DEFAULT_LATENCY_THRESHOLD)),
        "error_threshold":      float(annotations.get("grafana.com/error-slo", DEFAULT_ERROR_THRESHOLD)),
        "saturation_threshold": float(annotations.get("grafana.com/saturation-threshold", DEFAULT_SAT_THRESHOLD)),
        "oncall_team":          oncall_team,
        "runbook_base_url":     annotations.get("grafana.com/runbook-url", f"{DEFAULT_RUNBOOK_BASE}/{alliance}/{name}"),
    }


def write_services_txt(services: list[dict], path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(svc["name"] for svc in services) + "\n")
    print(f"  ✅ Wrote {len(services)} services to {path}")


def write_tfvars(services: list[dict], path: Path):
    lines = ["# Auto-generated by sync-from-catalog.py — do not edit manually\n"]
    lines.append("services = {")
    for svc in services:
        lines.append(f"""
  "{svc['name']}" = {{
    alliance              = "{svc['alliance']}"
    tier                  = "{svc['tier']}"
    latency_threshold     = {svc['latency_threshold']}
    error_threshold       = {svc['error_threshold']}
    saturation_threshold  = {svc['saturation_threshold']}
    oncall_team           = "{svc['oncall_team']}"
    runbook_base_url      = "{svc['runbook_base_url']}"
  }}""")
    lines.append("}\n")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    print(f"  ✅ Wrote {len(services)} services to {path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--url",     default=os.environ.get("GRAFANA_URL"))
    parser.add_argument("--token",   default=os.environ.get("GRAFANA_TOKEN"))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if not args.url or not args.token:
        print("ERROR: Provide --url and --token (or GRAFANA_URL / GRAFANA_TOKEN env vars)")
        sys.exit(1)

    print(f"Fetching services from {args.url}...")
    raw_entities = get_services(args.url, args.token)
    services = [infer_service_config(e) for e in raw_entities]
    print(f"Found {len(services)} services\n")

    if args.dry_run:
        print(json.dumps(services, indent=2))
        sys.exit(0)

    write_services_txt(services, Path("service-registry/services.txt"))
    write_tfvars(services, Path("terraform/catalog.auto.tfvars"))

    print(f"\nNext: cd terraform && terraform plan && terraform apply")
